name: install

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install dependancies
        run: |
          sudo apt-get install -y binutils cmake g++-13

      - name: Install
        run: |
          CC=gcc-13 CXX=g++-13 python setup.py install 
          pyinstaller ./sprtop/sprtop.py